title : 烟雨平生 
tagline: stop, look, and listen 
author :
  name : Peter Liu 
  email : lyilei@gmail.com 
  github : lyilei
  twitter : lyilei 
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
 
nav: 
  - title: home
    url: /
    describe: 主页
  - title: archive 
    url: /archive
    describe: 归档 
  - title: categories 
    url: /categories
    describe: 分类
  - title: tags
    url: /tags
    describe: 标签
  - title: about
    url: /about
    describe: 关于俺

